name: 'Validate and Check TF Code/Plan on Pull Request'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: 'Run Init on 01'
        run: cd terraform/01-create-s3-bucket && terraform init
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      - name: 'Run Plan on 01'
        run: cd terraform/01-create-s3-bucket && terraform plan
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}