name: 'Validate and Check TF Code/Plan on Pull Request'
on:
  - pull_request
jobs:
  lint-init-and-plan:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: 'Run Init on 01'
        run: cd terraform/01-create-s3-bucket && terraform init
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      - name: 'Run Plan on 01'
        run: cd terraform/01-create-s3-bucket && terraform plan
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      - name: 'Run Init on 02'
        run: cd terraform/02-configure-rubrik-archive-s3 && terraform init
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
          TF_VAR_CDM_NODE_IP: ${{ secrets.TF_VAR_CDM_NODE_IP }}
          TF_VAR_CDM_USERNAME: ${{ secrets.TF_VAR_CDM_USERNAME }}
          TF_VAR_CDM_PASSWORD: ${{ secrets.TF_VAR_CDM_PASSWORD }}
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
          TF_VAR_KMS_ID: ${{ secrets.TF_VAR_KMS_ID }}
      - name: 'Run Plan on 02'
        run: cd terraform/02-configure-rubrik-archive-s3 && terraform plan
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
          TF_VAR_CDM_NODE_IP: ${{ secrets.TF_VAR_CDM_NODE_IP }}
          TF_VAR_CDM_USERNAME: ${{ secrets.TF_VAR_CDM_USERNAME }}
          TF_VAR_CDM_PASSWORD: ${{ secrets.TF_VAR_CDM_PASSWORD }}
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
          TF_VAR_KMS_ID: ${{ secrets.TF_VAR_KMS_ID }}